# lag Prüfungssolver 9000


In [22]:
import numpy as np
import math
from random import random, randint
from util.core import mnull, mrref
import util.core as co
from IPython.display import display, Math

print(f"Precision: {np.finfo(float).eps}")

Precision: 2.220446049250313e-16


### Testing

In [23]:
m = np.array(
    [
        [1, 2, 3],
        [-4, -5, - 6],
        [12, 9.12312, -8.31231],
    ]
)
v= [1,2,3,4]

co.display_coefficient_matrix(m)
co.display_matrix(m)
co.display_vector(v)

print(np.array([1,3,4]) - np.array([2,3,3]))  

# skalare matrixmultiplikation
co.display_matrix(m * 2)

print(np.degrees(np.pi)) # 180
print(np.radians(180)) # pi


a = [1,0]
b = [0,1]
print(np.degrees(co.angle_between_vectors(a,b)))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

[-1  0  1]


<IPython.core.display.Math object>

180.0
3.141592653589793
CCW turn
90.0


### Polarkoordinaten zu kartesischen Koordinaten NNHCXF

Geben Sie die kartesischen Koordinaten der Vektoren an.
`[vx vy]=r*[cos(phi) sin(phi)]`\
Befehle: `np.array, np.cos, np.sin, print`\
a)


In [24]:
r = 5.0
phi = 216.9  # in Grad
degree = 2 * np.pi / 360  #
vv = r * np.array([np.cos(phi * degree), np.sin(phi * degree)])
print(vv)

[-3.99842329 -3.00210113]


### Beispiel 7.12 Hesse-Normalenform Koordinatenform 1V9ECJ

In [25]:
E = [15,-12,16,-184]
P = [-19,37,18]

print(co.distance_to_plane_hesse(P, E))

[25.]


### Beispiel 7.10 Abstand Punkt Ebene 2MZJ54

In [26]:
P = [10, 10, 10]
E = [50, 10, -32]
v = [21, 0, 20]
w = [42, 20, 40]

EP = np.array(P)- np.array(E)
paralellogramm_fl = np.linalg.norm(np.cross(v, w))
paralellopid_vol = np.dot(EP,np.cross(v, w))
distance = paralellopid_vol / paralellogramm_fl

print(distance)

58.0


### Beispiel 8.3 Schnittmengen qualitativ: Homogene LGS GL27L6
Ebene $E_1$, $E_2$ und $E_3$ geschnitten. Wie sieht die Schnittmenge $E_1 \land E_2 \land E_3$ aus?

$$ \begin{vmatrix}
0x&+9y&+8z&=&0\\
8x&+9y&+6z&=&0\\
10x&+0y&+6z&=&0
\end{vmatrix}
\quad\rightarrow\quad
\begin{vmatrix}
2x&+0y&+8z&=&0\\
0x&+9y&+8z&=&0\\
0x&+0y&+34z&=&0
\end{vmatrix}$$

In [27]:
print("a)")
lgs = np.array([
    [0,9,8],
    [8,9,6],
    [10,0,6]
])

co.solve_null_space(lgs)
# Schnittpunkt auf nullpunkt, keine freien variablen

a)


<IPython.core.display.Math object>

### Beispiel 8.12 Homogene lineare Gleichungssysteme 801980
Bestimme die Lösungsmenge der homogenen linearen Gleichungsysteme\
a)
$$ \begin{vmatrix}
E_1:&3x&+3y&+-12z&=&0\\
E_2:&1x&+0y&-4z&=&0\\
E_3:&5x&+2y&-20z&=&0
\end{vmatrix}

In [28]:
lgs = np.array(
    [
        [3, 3, -12],
        [1, 0, -4],
        [5, +2, -20],
    ]
)

print("a)")
co.solve_null_space(lgs)

a)


<IPython.core.display.Math object>

In [29]:
lgs = np.array(
    [
        [3, 5, -5],
        [0, 1, -3],
        [0, 2, -5],
    ]
)

print("b)")
# print(richtungsvektor) # [] -> keine Richtungsvektoren vorhanden. Nur die Triviale lösung erfüllt das lgs. (0,0,0)

co.solve_null_space(lgs)


b)


<IPython.core.display.Math object>

In [30]:
lgs = np.array(
    [
        [1, 3, 1],
        [0, 1, 1],
        [0, 2, 2],
    ]
)

print("c)")
co.solve_null_space(lgs)

c)


<IPython.core.display.Math object>

### Beispiel 8.4 Schnittmengen qualitativ: Inhomogene LGS EM75PE

In [31]:
print("a)")
lgs = np.array([
    [2,1,-2,1],
    [1,8,-4,10],
    [6,-1,18,81],
])

# co.particular_solution(lgs)
co.solve_general_solution(lgs)
# schnittpunkt

a)


<IPython.core.display.Math object>

In [32]:
print("b)")
lgs = np.array([
    [2,1,-2,7],
    [1,8,-4,20],
    [-3,+6,0,6],
])

# co.particular_solution(lgs)
co.solve_general_solution(lgs)
# schnittgerade

b)


<IPython.core.display.Math object>

### Beispiel 8.13 Richtungsvektoren und NullraumV5JXDD

Mehrere Richtungsvektoren

$$ \begin{vmatrix}
1x&+2y&+3z&=&0\\
\end{vmatrix}

In [33]:
lgs = np.array(
    [
        [1, 2, 3],
    ]
)
co.solve_null_space(lgs)


<IPython.core.display.Math object>

### Beispiel 8.14 Nullraum QWDLIG

In [34]:
print("a)")
lgs = np.array(
    [
        [5, 6, 1],
    ]
)
co.solve_null_space(lgs, 1)

a)
[[-1.2 -0.2]
 [ 1.   0. ]
 [ 0.   1. ]]


<IPython.core.display.Math object>

# Kapitel 9 Matrixalgebra

### Beispiel 9.9 Produkt von zwei Matrizen CKZ2V1

In [35]:
A = np.array(
    [
        [0, 4, 2],
        [2, -1, 5],
        [6, 0, -3],
    ]
)

B = np.array(
    [
        [4, 1, 9],
        [5, 4, 2],
        [-3, 5, 2],
    ]
)

C = np.array(
    [
        [5, 6],
        [5, 1],
    ]
)

D = np.array(
    [
        [-1, 3],
        [5, 0],
    ]
)

E = np.array(
    [
        [7, -2, 4, 0],
        [3, 3, 0, 1],
    ]
)

F = np.array(
    [
        [0, 9],
        [2, 0],
        [2, 4],
        [0, -2],
    ]
)

print("a")
co.display_matrix(np.matmul(A, B))
print("b")
co.display_matrix(np.matmul(C, D))
print("c")
co.display_matrix(np.matmul(E, F))
# print("d")
# co.display_matrix(np.matmul(E, C)) # keine lösung

a


<IPython.core.display.Math object>

b


<IPython.core.display.Math object>

c


<IPython.core.display.Math object>

### Beispiel 9.22 Linearkombination LQF58M


In [36]:
u = np.array([-6, 6, 9])
v = np.array([0, -2, 1])
w = np.array([0, 7, -7])
l = np.array([-1, 6, 1])

A = np.transpose(np.array([u, v, w])) # must be transposed to get a coefficient matrix
print("a)")
print(-1 * u + 6 * v + 1 * w)

print("b)")
print(A)
print(f"Solution:")
print(np.matmul(A, l))

a)
[  6 -11 -10]
b)
[[-6  0  0]
 [ 6 -2  7]
 [ 9  1 -7]]
Solution:
[  6 -11 -10]


### Beispiel 9.23 Linearkombination T46Q97


In [37]:
print("a)")
M = np.array(
    [
        [1, -1, 0],
        [6, 0, -5],
        [0, 5, -1],
    ]
)
v = np.array(
    [
        -8,
        +3,
        -2,
    ]
)

co.display_vector(np.matmul(M, v))

print("b)")
M = np.array(
    [
        [0, 1, 3],
        [-1, 0, -1],
        [3, 4, 15],
    ]
)
v = np.array(
    [
        -4,
        3,
        1,
    ]
)

co.display_vector(np.matmul(M, v))

a)


<IPython.core.display.Math object>

b)


<IPython.core.display.Math object>

### Beispiel 9.24 Matrix mal Vektor = Einsetzen in Koeffizientenmatrix CNNZ8U


In [38]:
A = np.array(
    [
        [1, -1, 2],
        [6, 1, -1],
    ]
)
x_p = [1, -2, -1]
x_h = [-1, 13, 7]
print("a)")
print(np.dot(A, x_p))
print("b)")
print(np.matmul(A, x_p))  # matmul = matrix produkt
print("c)")
print(np.dot(A, x_p))

a)
[1 5]
b)
[1 5]
c)
[1 5]


# Kapitel 10 Lineare Abbildungen


### Beispiel 10.3 Linearitat IMSW1Y


In [39]:
print("a)")
w = co.random_vector(3)
co.solve_check_linearity(3, lambda v: np.dot(v, w))
print("b)")
co.solve_check_linearity(3, lambda v: 5 * v[0] - v[1] + 1)

a)
✔️ Null Vector:  0.0 is null
✔️ Homogenity:   L(lambda * v) = 0.3517271467363267 =?= lambda * L(v) = 0.3517271467363267
✔️ Additivity:   L(v + w) = 1.9549019833018764 =?= L(v) + L(w) = 1.9549019833018764
✔️ Transformation is linear
b)
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 2.222467708824104 =?= lambda * L(v) = 2.011027818274203
❌ Additivity:   L(v + w) = 3.6337979126149484 =?= L(v) + L(w) = 4.6337979126149484
❌ Transformation is NOT linear


### Beispiel 10.8 Linearität YHRNU8


In [40]:
print("a")
gamma = random()
co.solve_check_linearity(
    2,
    lambda v: [
        math.cos(gamma) * v[0],
        math.sin(gamma) * v[1],
    ],
)
print("b")
co.solve_check_linearity(2, lambda v: np.dot(v, v))
print("c")
co.solve_check_linearity(2, lambda v: 5 * v[0] + 2 * v[1])
print("d")
co.solve_check_linearity(2, lambda v: np.multiply(-1, v))

a
✔️ Null Vector:  [np.float64(0.0), np.float64(0.0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.2003261562470318), np.float64(0.6081421119003266)] =?= lambda * L(v) = [0.20032616 0.60814211]
✔️ Additivity:   L(v + w) = [np.float64(0.7109933891329899), np.float64(1.125506074998603)] =?= L(v) + L(w) = [0.71099339 1.12550607]
✔️ Transformation is linear
b
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.036986151291584266 =?= lambda * L(v) = 0.060032590467225755
❌ Additivity:   L(v + w) = 1.03628914805315 =?= L(v) + L(w) = 0.595783696311381
❌ Transformation is NOT linear
c
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(lambda * v) = 2.864330854696733 =?= lambda * L(v) = 2.8643308546967328
✔️ Additivity:   L(v + w) = 10.484115723201734 =?= L(v) + L(w) = 10.484115723201736
✔️ Transformation is linear
d
✔️ Null Vector:  [0 0] is null
✔️ Homogenity:   L(lambda * v) = [-0.18077445 -0.33150962] =?= lambda * L(v) = [-0.18077445 -0.33150962]
✔️ Additivity:   L(v + w) = [-1

In [41]:
print("e")
co.solve_check_linearity(
    2,
    lambda v: [
        math.cos(v[0]),
        math.sin(v[1]),
    ],
)
print("f")
co.solve_check_linearity(
    2,
    lambda v: [
        0,
        v[0] * v[1],
    ],
)
print("g")
co.solve_check_linearity(
    2,
    lambda v: [
        v[0] + v[1],
        v[0],
    ],
)
print("h")
co.solve_check_linearity(2, lambda v: v[0])

e
❌ Null Vector:  [1.0, 0.0] is NOT null
❌ Homogenity:   L(lambda * v) = [0.8123127666750966, 0.49363990505933625] =?= lambda * L(v) = [0.73379973 0.49036985]
❌ Additivity:   L(v + w) = [0.783088571671889, 0.8461998680208243] =?= L(v) + L(w) = [1.78578708 0.96544169]
❌ Transformation is NOT linear
f
✔️ Null Vector:  [0, np.int64(0)] is null
❌ Homogenity:   L(lambda * v) = [0, np.float64(0.11898535132602606)] =?= lambda * L(v) = [0.         0.13847945]
❌ Additivity:   L(v + w) = [0, np.float64(0.403067298339832)] =?= L(v) + L(w) = [0.         0.21489845]
❌ Transformation is NOT linear
g
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.6853378532537852), np.float64(0.2704564348407646)] =?= lambda * L(v) = [0.68533785 0.27045643]
✔️ Additivity:   L(v + w) = [np.float64(3.2286846966266194), np.float64(1.51678863608598)] =?= L(v) + L(w) = [3.2286847  1.51678864]
✔️ Transformation is linear
h
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(lamb

In [42]:
print("i")
co.solve_check_linearity(2, lambda v: v[0] ** 2)
print("j")
co.solve_check_linearity(2, lambda v: v[0] + 1)
print("k")
co.solve_check_linearity(
    2,
    lambda v: [
        3 * v[0] - 4 * v[1],
        v[0] + 5 * v[1],
    ],
)

i
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.32161814049747744 =?= lambda * L(v) = 0.5506542550872296
❌ Additivity:   L(v + w) = 3.662966447501717 =?= L(v) + L(w) = 1.8318770534652105
❌ Transformation is NOT linear
j
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 1.2822621892813977 =?= lambda * L(v) = 0.6534802872434693
❌ Additivity:   L(v + w) = 2.155573248185473 =?= L(v) + L(w) = 3.155573248185473
❌ Transformation is NOT linear
k
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.7268717006414569), np.float64(1.2320409896051712)] =?= lambda * L(v) = [0.7268717  1.23204099]
✔️ Additivity:   L(v + w) = [np.float64(3.658459427757271), np.float64(2.8182593662445257)] =?= L(v) + L(w) = [3.65845943 2.81825937]
✔️ Transformation is linear
