# lag Prüfungssolver 9000


In [27]:
import numpy as np
import sympy as sp
import math
from random import random, randint
from util.core import mnull, mrref
import util.core as co
from util.objects import Line, Plane
from util.linearity import linearity
from IPython.display import display, Math

print(f"Precision: {np.finfo(float).eps}")

Precision: 2.220446049250313e-16


### Testing

In [28]:
m = np.array(
    [
        [1, 2, 3],
        [-4, -5, - 6],
        [12, 9.12312, -8.31231],
    ]
)
v= [1,2,3,4]

co.display_coefficient_matrix(m)
co.display_matrix(m)
co.display_vector(v)

print(np.array([1,3,4]) - np.array([2,3,3]))  

# skalare matrixmultiplikation
co.display_matrix(m * 2)

print(np.degrees(np.pi)) # 180
print(np.radians(180)) # pi


a = [1,0]
b = [0,1]
print(np.degrees(co.angle_between_vectors(a,b)))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

[-1  0  1]


<IPython.core.display.Math object>

180.0
3.141592653589793
CCW turn
90.0


### Polarkoordinaten zu kartesischen Koordinaten NNHCXF

Geben Sie die kartesischen Koordinaten der Vektoren an.
`[vx vy]=r*[cos(phi) sin(phi)]`\
Befehle: `np.array, np.cos, np.sin, print`\
a)


In [29]:
r = 5.0
phi = 216.9  # in Grad
degree = 2 * np.pi / 360  #
vv = r * np.array([np.cos(phi * degree), np.sin(phi * degree)])
print(vv)

[-3.99842329 -3.00210113]


### Beispiel 7.12 Hesse-Normalenform Koordinatenform 1V9ECJ

In [30]:
E = [15,-12,16,-184]
P = [-19,37,18]

print(co.distance_to_plane_hesse(P, E))

[25.]


### Beispiel 7.10 Abstand Punkt Ebene 2MZJ54

In [31]:
P = [10, 10, 10]
E = [50, 10, -32]
v = [21, 0, 20]
w = [42, 20, 40]

EP = np.array(P)- np.array(E)
paralellogramm_fl = np.linalg.norm(np.cross(v, w))
paralellopid_vol = np.dot(EP,np.cross(v, w))
distance = paralellopid_vol / paralellogramm_fl

print(distance)

58.0


### Beispiel 8.3 Schnittmengen qualitativ: Homogene LGS GL27L6
Ebene $E_1$, $E_2$ und $E_3$ geschnitten. Wie sieht die Schnittmenge $E_1 \land E_2 \land E_3$ aus?

$$ \begin{vmatrix}
0x&+9y&+8z&=&0\\
8x&+9y&+6z&=&0\\
10x&+0y&+6z&=&0
\end{vmatrix}
\quad\rightarrow\quad
\begin{vmatrix}
2x&+0y&+8z&=&0\\
0x&+9y&+8z&=&0\\
0x&+0y&+34z&=&0
\end{vmatrix}$$

In [32]:
print("a)")
lgs = np.array([
    [0,9,8],
    [8,9,6],
    [10,0,6]
])

co.solve_null_space(lgs)
# Schnittpunkt auf nullpunkt, keine freien variablen

a)


<IPython.core.display.Math object>

### Beispiel 8.12 Homogene lineare Gleichungssysteme 801980
Bestimme die Lösungsmenge der homogenen linearen Gleichungsysteme\
a)
$$ \begin{vmatrix}
E_1:&3x&+3y&+-12z&=&0\\
E_2:&1x&+0y&-4z&=&0\\
E_3:&5x&+2y&-20z&=&0
\end{vmatrix}

In [33]:
lgs = np.array(
    [
        [3, 3, -12],
        [1, 0, -4],
        [5, +2, -20],
    ]
)

print("a)")
co.solve_null_space(lgs)

a)


<IPython.core.display.Math object>

In [34]:
lgs = np.array(
    [
        [3, 5, -5],
        [0, 1, -3],
        [0, 2, -5],
    ]
)

print("b)")
# print(richtungsvektor) # [] -> keine Richtungsvektoren vorhanden. Nur die Triviale lösung erfüllt das lgs. (0,0,0)

co.solve_null_space(lgs)


b)


<IPython.core.display.Math object>

In [35]:
lgs = np.array(
    [
        [1, 3, 1],
        [0, 1, 1],
        [0, 2, 2],
    ]
)

print("c)")
co.solve_null_space(lgs)

c)


<IPython.core.display.Math object>

### Beispiel 8.4 Schnittmengen qualitativ: Inhomogene LGS EM75PE

In [36]:
print("a)")
lgs = np.array([
    [2,1,-2,1],
    [1,8,-4,10],
    [6,-1,18,81],
])

# co.particular_solution(lgs)
co.solve_general_solution(lgs)
# schnittpunkt

a)


<IPython.core.display.Math object>

In [37]:
print("b)")
lgs = np.array([
    [2,1,-2,7],
    [1,8,-4,20],
    [-3,+6,0,6],
])

# co.particular_solution(lgs)
co.solve_general_solution(lgs)
# schnittgerade

b)


<IPython.core.display.Math object>

### Beispiel 8.13 Richtungsvektoren und NullraumV5JXDD

Mehrere Richtungsvektoren

$$ \begin{vmatrix}
1x&+2y&+3z&=&0\\
\end{vmatrix}

In [38]:
lgs = np.array(
    [
        [1, 2, 3],
    ]
)
co.solve_null_space(lgs)


<IPython.core.display.Math object>

### Beispiel 8.14 Nullraum QWDLIG

In [39]:
print("a)")
lgs = np.array(
    [
        [5, 6, 1],
    ]
)
co.solve_null_space(lgs, 1)

a)
[[-1.2 -0.2]
 [ 1.   0. ]
 [ 0.   1. ]]


<IPython.core.display.Math object>

# Kapitel 9 Matrixalgebra

### Beispiel 9.9 Produkt von zwei Matrizen CKZ2V1

In [40]:
A = np.array(
    [
        [0, 4, 2],
        [2, -1, 5],
        [6, 0, -3],
    ]
)

B = np.array(
    [
        [4, 1, 9],
        [5, 4, 2],
        [-3, 5, 2],
    ]
)

C = np.array(
    [
        [5, 6],
        [5, 1],
    ]
)

D = np.array(
    [
        [-1, 3],
        [5, 0],
    ]
)

E = np.array(
    [
        [7, -2, 4, 0],
        [3, 3, 0, 1],
    ]
)

F = np.array(
    [
        [0, 9],
        [2, 0],
        [2, 4],
        [0, -2],
    ]
)

print("a")
co.display_matrix(np.matmul(A, B))
print("b")
co.display_matrix(np.matmul(C, D))
print("c")
co.display_matrix(np.matmul(E, F))
# print("d")
# co.display_matrix(np.matmul(E, C)) # keine lösung

a


<IPython.core.display.Math object>

b


<IPython.core.display.Math object>

c


<IPython.core.display.Math object>

### Beispiel 9.22 Linearkombination LQF58M


In [41]:
u = np.array([-6, 6, 9])
v = np.array([0, -2, 1])
w = np.array([0, 7, -7])
l = np.array([-1, 6, 1])

A = np.transpose(np.array([u, v, w])) # must be transposed to get a coefficient matrix
print("a)")
print(-1 * u + 6 * v + 1 * w)

print("b)")
print(A)
print(f"Solution:")
print(np.matmul(A, l))

a)
[  6 -11 -10]
b)
[[-6  0  0]
 [ 6 -2  7]
 [ 9  1 -7]]
Solution:
[  6 -11 -10]


### Beispiel 9.23 Linearkombination T46Q97


In [42]:
print("a)")
M = np.array(
    [
        [1, -1, 0],
        [6, 0, -5],
        [0, 5, -1],
    ]
)
v = np.array(
    [
        -8,
        +3,
        -2,
    ]
)

co.display_vector(np.matmul(M, v))

print("b)")
M = np.array(
    [
        [0, 1, 3],
        [-1, 0, -1],
        [3, 4, 15],
    ]
)
v = np.array(
    [
        -4,
        3,
        1,
    ]
)

co.display_vector(np.matmul(M, v))

a)


<IPython.core.display.Math object>

b)


<IPython.core.display.Math object>

### Beispiel 9.24 Matrix mal Vektor = Einsetzen in Koeffizientenmatrix CNNZ8U


In [43]:
A = np.array(
    [
        [1, -1, 2],
        [6, 1, -1],
    ]
)
x_p = [1, -2, -1]
x_h = [-1, 13, 7]
print("a)")
print(np.dot(A, x_p))
print("b)")
print(np.matmul(A, x_p))  # matmul = matrix produkt
print("c)")
print(np.dot(A, x_p))

a)
[1 5]
b)
[1 5]
c)
[1 5]


# Kapitel 10 Lineare Abbildungen


### Beispiel 10.3 Linearitat IMSW1Y


In [44]:
print("a)")
w = co.random_vector(3)
co.solve_check_linearity(3, lambda v: np.dot(v, w))
print("b)")
co.solve_check_linearity(3, lambda v: 5 * v[0] - v[1] + 1)

a)
✔️ Null Vector:  0.0 is null
✔️ Homogenity:   L(lambda * v) = 0.3034186412391766 =?= lambda * L(v) = 0.30341864123917656
✔️ Additivity:   L(v + w) = 1.2359320105842395 =?= L(v) + L(w) = 1.2359320105842395
✔️ Transformation is linear
b)
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 1.4472579761332836 =?= lambda * L(v) = 0.7889272547243678
❌ Additivity:   L(v + w) = 5.773082073772147 =?= L(v) + L(w) = 6.773082073772148
❌ Transformation is NOT linear


### Beispiel 10.8 Linearität YHRNU8


In [45]:
print("a")
gamma = random()
co.solve_check_linearity(
    2,
    lambda v: [
        math.cos(gamma) * v[0],
        math.sin(gamma) * v[1],
    ],
)
print("b")
co.solve_check_linearity(2, lambda v: np.dot(v, v))
print("c")
co.solve_check_linearity(2, lambda v: 5 * v[0] + 2 * v[1])
print("d")
co.solve_check_linearity(2, lambda v: np.multiply(-1, v))

a
✔️ Null Vector:  [np.float64(0.0), np.float64(0.0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.1425620755548225), np.float64(0.010495712866273252)] =?= lambda * L(v) = [0.14256208 0.01049571]
✔️ Additivity:   L(v + w) = [np.float64(0.9919782406126756), np.float64(0.03990813217556753)] =?= L(v) + L(w) = [0.99197824 0.03990813]
✔️ Transformation is linear
b
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.10678081656146834 =?= lambda * L(v) = 0.39928413165794346
❌ Additivity:   L(v + w) = 3.747272985316092 =?= L(v) + L(w) = 2.1836480804575578
❌ Transformation is NOT linear
c
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(lambda * v) = 2.485749141379625 =?= lambda * L(v) = 2.485749141379625
✔️ Additivity:   L(v + w) = 10.153366755502415 =?= L(v) + L(w) = 10.153366755502415
✔️ Transformation is linear
d
✔️ Null Vector:  [0 0] is null
✔️ Homogenity:   L(lambda * v) = [-0.00833406 -0.48835511] =?= lambda * L(v) = [-0.00833406 -0.48835511]
✔️ Additivity:   L(v + w) = 

In [46]:
print("e")
co.solve_check_linearity(
    2,
    lambda v: [
        math.cos(v[0]),
        math.sin(v[1]),
    ],
)
print("f")
co.solve_check_linearity(
    2,
    lambda v: [
        0,
        v[0] * v[1],
    ],
)
print("g")
co.solve_check_linearity(
    2,
    lambda v: [
        v[0] + v[1],
        v[0],
    ],
)
print("h")
co.solve_check_linearity(2, lambda v: v[0])

e
❌ Null Vector:  [1.0, 0.0] is NOT null
❌ Homogenity:   L(lambda * v) = [0.8656153374537833, 0.46602876683729466] =?= lambda * L(v) = [0.31239015 0.4234752 ]
❌ Additivity:   L(v + w) = [-0.0414683171158691, 0.8106501040875722] =?= L(v) + L(w) = [1.36797435 0.83283844]
❌ Transformation is NOT linear
f
✔️ Null Vector:  [0, np.int64(0)] is null
❌ Homogenity:   L(lambda * v) = [0, np.float64(0.10023275034919812)] =?= lambda * L(v) = [0.        0.1113792]
❌ Additivity:   L(v + w) = [0, np.float64(0.7973283860803572)] =?= L(v) + L(w) = [0.         0.40897789]
❌ Transformation is NOT linear
g
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.38570524406948886), np.float64(0.21986998398814886)] =?= lambda * L(v) = [0.38570524 0.21986998]
✔️ Additivity:   L(v + w) = [np.float64(2.566094735688583), np.float64(1.25868207783632)] =?= L(v) + L(w) = [2.56609474 1.25868208]
✔️ Transformation is linear
h
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(la

In [47]:
print("i")
co.solve_check_linearity(2, lambda v: v[0] ** 2)
print("j")
co.solve_check_linearity(2, lambda v: v[0] + 1)
print("k")
co.solve_check_linearity(
    2,
    lambda v: [
        3 * v[0] - 4 * v[1],
        v[0] + 5 * v[1],
    ],
)

i
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.153196801534947 =?= lambda * L(v) = 0.16134218080911586
❌ Additivity:   L(v + w) = 0.9022504983064839 =?= L(v) + L(w) = 0.458992850475882
❌ Transformation is NOT linear
j
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 1.0073171909503595 =?= lambda * L(v) = 0.03748913604579107
❌ Additivity:   L(v + w) = 1.4924106318280081 =?= L(v) + L(w) = 2.492410631828008
❌ Transformation is NOT linear
k
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.2135697373483111), np.float64(0.12253313046129777)] =?= lambda * L(v) = [0.21356974 0.12253313]
✔️ Additivity:   L(v + w) = [np.float64(2.1613379082829636), np.float64(1.692354521797986)] =?= L(v) + L(w) = [2.16133791 1.69235452]
✔️ Transformation is linear


Line Object

In [48]:
l1 = Line(np.array((1,2,3)),np.array((1,2,3)))
l1.display()

<IPython.core.display.Math object>

Plane intersection

In [49]:
p1 = Plane(np.array((2,1,-2,-1)))
p1_1 = Plane(np.array((2,1,-2,-1)))
p2 = Plane(np.array((1,8,-4,10)))
p4_same_as_p1 = Plane(np.array((4,2,-4,-2)))
p3_paralell_to_p2 = Plane(np.array((2,16,-8,10)))
p5 = Plane(np.array((-5,2,3,10)))

Plane.intersect_all(p1, p2, p5)


Intersection 1#:
Line: Aufpunkt: [-1.2  1.4  0. ], Richtungsvektor [0.8 0.4 1. ]
Intersection 2#:
Line: Aufpunkt: [-1.33333333  1.66666667  0.        ], Richtungsvektor [0.77777778 0.44444444 1.        ]
Intersection 3#:
Line: Aufpunkt: [-1.42857143  1.42857143  0.        ], Richtungsvektor [0.76190476 0.4047619  1.        ]


<IPython.core.display.Math object>

In [50]:
p1 = Plane(np.array((2,1,-2,-1)))
p2 = Plane(np.array((1,8,-4,10)))
p3 = Plane(np.array((6,-1,18,81)))

p3_paralell_to_p2 = Plane(np.array((2,16,-8,10)))

intersection_lines = Plane.intersect_all(p1, p2, p3)

Line.intersect_all(*intersection_lines)

Intersection 1#:
Line: Aufpunkt: [-1.2  1.4  0. ], Richtungsvektor [0.8 0.4 1. ]
Intersection 2#:
Line: Aufpunkt: [ 10. -21.   0.], Richtungsvektor [-2.  6.  1.]
Intersection 3#:
Line: Aufpunkt: [13.42857143 -0.42857143  0.        ], Richtungsvektor [-2.85714286  0.85714286  1.        ]


<IPython.core.display.Math object>

[array([2., 3., 0.])]

Linearity Test

In [ ]:
phi = sp.symbols("phi", real=True)
transformation = lambda x, y: sp.Matrix((sp.cos(phi) * x, sp.sin(phi) * y))
linearity(transformation, 2)

TypeError: 
Data type not understood; expecting list of lists or lists of values.

In [52]:
transformation3 = lambda x, y: x + 1
linearity(transformation3, 2)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

Is NOT additive. ❌


<IPython.core.display.Math object>

<IPython.core.display.Math object>

Is NOT homogenous. ❌
 Linearity does not check out. 🍆
