# lag Prüfungssolver 9000


In [1]:
import numpy as np
import math
from random import random, randint
from util.core import mnull, mrref, linear_combination, check_linearity
import util.core as co
from IPython.display import display, Math

print(f"Precision: {np.finfo(float).eps}")

Precision: 2.220446049250313e-16


### Polarkoordinaten zu kartesischen Koordinaten NNHCXF

Geben Sie die kartesischen Koordinaten der Vektoren an.
`[vx vy]=r*[cos(phi) sin(phi)]`\
Befehle: `np.array, np.cos, np.sin, print`\
a)


In [2]:
r = 5.0
phi = 216.9  # in Grad
degree = 2 * np.pi / 360  #
vv = r * np.array([np.cos(phi * degree), np.sin(phi * degree)])
print(vv)

[-3.99842329 -3.00210113]


### Beispiel 8.3 Schnittmengen qualitativ: Homogene LGS GL27L6
Ebene $E_1$, $E_2$ und $E_3$ geschnitten. Wie sieht die Schnittmenge $E_1 \land E_2 \land E_3$ aus?

$$ \begin{vmatrix}
0x&+9y&+8z&=&0\\
8x&+9y&+6z&=&0\\
10x&+0y&+6z&=&0
\end{vmatrix}
\quad\rightarrow\quad
\begin{vmatrix}
2x&+0y&+8z&=&0\\
0x&+9y&+8z&=&0\\
0x&+0y&+34z&=&0
\end{vmatrix}$$

In [28]:
print("a)")
lgs = np.array([
    [0,9,8],
    [8,9,6],
    [10,0,6]
])

co.display_null_space(lgs)
# Schnittpunkt auf nullpunkt, keine freien variablen

a)


<IPython.core.display.Math object>

### Beispiel 8.12 Homogene lineare Gleichungssysteme 801980
Bestimme die Lösungsmenge der homogenen linearen Gleichungsysteme\
a)
$$ \begin{vmatrix}
E_1:&3x&+3y&+-12z&=&0\\
E_2:&1x&+0y&-4z&=&0\\
E_3:&5x&+2y&-20z&=&0
\end{vmatrix}

In [26]:
lgs = np.array(
    [
        [3, 3, -12],
        [1, 0, -4],
        [5, +2, -20],
    ]
)

print("a)")
co.display_null_space(lgs)

a)


<IPython.core.display.Math object>

In [30]:
lgs = np.array(
    [
        [3, 5, -5],
        [0, 1, -3],
        [0, 2, -5],
    ]
)

print("b)")
richtungsvektor = mnull(lgs)
# print(richtungsvektor) # [] -> keine Richtungsvektoren vorhanden. Nur die Triviale lösung erfüllt das lgs. (0,0,0)

co.display_null_space(lgs)


b)


<IPython.core.display.Math object>

In [6]:
lgs = np.array(
    [
        [1, 3, 1],
        [0, 1, 1],
        [0, 2, 2],
    ]
)

print("c)")
co.display_null_space(lgs)

c)


<IPython.core.display.Math object>

### Beispiel 8.4 Schnittmengen qualitativ: Inhomogene LGS EM75PE

In [ ]:
print("a)")
lgs = np.array([
    [2,1,-2,1],
    [1,8,-4,10],
    [6,-1,18,81],
])

# co.particular_solution(lgs)
co.display_general_solution(lgs)
# schnittpunkt

a)


<IPython.core.display.Math object>

In [ ]:
print("b)")
lgs = np.array([
    [2,1,-2,7],
    [1,8,-4,20],
    [-3,+6,0,6],
])

# co.particular_solution(lgs)
co.display_general_solution(lgs)
# schnittgerade

b)


<IPython.core.display.Math object>

### Beispiel 8.13 Richtungsvektoren und NullraumV5JXDD

Mehrere Richtungsvektoren

$$ \begin{vmatrix}
1x&+2y&+3z&=&0\\
\end{vmatrix}

In [22]:
lgs = np.array(
    [
        [1, 2, 3],
    ]
)
co.display_null_space(lgs)


<IPython.core.display.Math object>

### Beispiel 8.14 Nullraum QWDLIG

In [9]:
print("a)")
lgs = np.array(
    [
        [5, 6, 1],
    ]
)
co.display_null_space(lgs, 1)

a)
[[-1.2 -0.2]
 [ 1.   0. ]
 [ 0.   1. ]]


<IPython.core.display.Math object>

### Beispiel 9.22 Linearkombination LQF58M


In [10]:
u = np.array([-6, 6, 9])
v = np.array([0, -2, 1])
w = np.array([0, 7, -7])
l = np.array([-1, 6, 1])

A = np.transpose(np.array([u, v, w])) # must be transposed to get a coefficient matrix
print("a)")
print(-1 * u + 6 * v + 1 * w)

print("b)")
print(A)
print(f"Solution:")
print(np.matmul(A, l))

a)
[  6 -11 -10]
b)
[[-6  0  0]
 [ 6 -2  7]
 [ 9  1 -7]]
Solution:
[  6 -11 -10]


### Beispiel 9.23 Linearkombination T46Q97


In [11]:
print("a)")
M = np.array([
    [1, -1, 0],
    [6, 0, -5],
    [0, 5, -1]
    ])
v = np.array([-8,+3,-2])

print(np.matmul(M, v))

print("b)")
M = np.array([
    [0, 1, 3],
    [-1, 0, -1],
    [3, 4, 15]
    ])
v = np.array([-4,3,1])

print(np.matmul(M, v))


a)
[-11 -38  17]
b)
[ 6  3 15]


### Beispiel 9.24 Matrix mal Vektor = Einsetzen in Koeffizientenmatrix CNNZ8U


In [12]:
A = np.array([[1, -1, 2], [6, 1, -1]])
x_p = [1, -2, -1]
x_h = [-1, 13, 7]
print("a)")
print(np.dot(A, x_p))
print("b)")
print(np.matmul(A, x_p))  # matmul = matrix produkt
print("c)")
print(np.dot(A, x_p))

a)
[1 5]
b)
[1 5]
c)
[1 5]


# Kapitel 10 Lineare Abbildungen


### Beispiel 10.3 Linearitat IMSW1Y


In [13]:
print("a)")
w = co.random_vector(3)
check_linearity(3, lambda v: np.dot(v, w))
print("b)")
check_linearity(3, lambda v: 5 * v[0] - v[1] + 1)

a)
✔️ Null Vector:  0.0 is null
✔️ Homogenity:   L(lambda * v) = 0.22011609661387727 =?= lambda * L(v) = 0.22011609661387727
✔️ Additivity:   L(v + w) = 0.6269841296366818 =?= L(v) + L(w) = 0.6269841296366817
✔️ Transformation is linear
b)
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 1.0284274476207662 =?= lambda * L(v) = 0.2507268067491871
❌ Additivity:   L(v + w) = 2.261693806780472 =?= L(v) + L(w) = 3.2616938067804715
❌ Transformation is NOT linear


### Beispiel 10.8 Linearität YHRNU8


In [14]:
print("a")
gamma = random()
check_linearity(2, lambda v: [math.cos(gamma) * v[0], math.sin(gamma) * v[1]])
print("b")
check_linearity(2, lambda v: np.dot(v, v))
print("c")
check_linearity(2, lambda v: 5 * v[0] + 2 * v[1])
print("d")
check_linearity(2, lambda v: np.multiply(-1, v))

a
✔️ Null Vector:  [np.float64(0.0), np.float64(0.0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.11823531405510081), np.float64(0.016409503223381996)] =?= lambda * L(v) = [0.11823531 0.0164095 ]
✔️ Additivity:   L(v + w) = [np.float64(0.7204727616498761), np.float64(0.758573800031911)] =?= L(v) + L(w) = [0.72047276 0.7585738 ]
✔️ Transformation is linear
b
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.04673124013190439 =?= lambda * L(v) = 0.055550824786570904
❌ Additivity:   L(v + w) = 1.6184552702755286 =?= L(v) + L(w) = 1.103898146123562
❌ Transformation is NOT linear
c
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(lambda * v) = 1.1476596245365067 =?= lambda * L(v) = 1.147659624536507
✔️ Additivity:   L(v + w) = 8.38926583575262 =?= L(v) + L(w) = 8.38926583575262
✔️ Transformation is linear
d
✔️ Null Vector:  [0 0] is null
✔️ Homogenity:   L(lambda * v) = [-0.38990801 -0.11302333] =?= lambda * L(v) = [-0.38990801 -0.11302333]
✔️ Additivity:   L(v + w) = [-0

In [ ]:
print("e")
check_linearity(2, lambda v: [math.cos(v[0]), math.sin(v[1])])
print("f")
check_linearity(2, lambda v: [0, v[0] * v[1]])
print("g")
check_linearity(2, lambda v: [v[0] + v[1], v[0]])
print("h")
check_linearity(2, lambda v: v[0])

e
❌ Null Vector:  [1.0, 0.0] is NOT null
❌ Homogenity:   L(lambda * v) = [0.9956001502960777, 0.08546307702602465] =?= lambda * L(v) = [0.08244266 0.07824699]
❌ Additivity:   L(v + w) = [0.036135769109751255, 0.7723987623166307] =?= L(v) + L(w) = [1.43894023 0.81986157]
❌ Transformation is NOT linear
f
✔️ Null Vector:  [0, np.int64(0)] is null
❌ Homogenity:   L(lambda * v) = [0, np.float64(0.3228159812199928)] =?= lambda * L(v) = [0.         0.41708158]
❌ Additivity:   L(v + w) = [0, np.float64(2.108310812823122)] =?= L(v) + L(w) = [0.         1.05353045]
❌ Transformation is NOT linear
g
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.07109904286447127), np.float64(0.040721206506915984)] =?= lambda * L(v) = [0.07109904 0.04072121]
✔️ Additivity:   L(v + w) = [np.float64(1.7484837896686454), np.float64(0.6030412199175121)] =?= L(v) + L(w) = [1.74848379 0.60304122]
✔️ Transformation is linear
h
✔️ Null Vector:  0 is null
✔️ Homogenity:  

In [ ]:
print("i")
check_linearity(2, lambda v: v[0] ** 2)
print("j")
check_linearity(2, lambda v: v[0] + 1)
print("k")
check_linearity(2, lambda v: [3 * v[0] - 4 * v[1], v[0] + 5 * v[1]])

i
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.6065370420003633 =?= lambda * L(v) = 0.7775649349250873
❌ Additivity:   L(v + w) = 1.2709493355679793 =?= L(v) + L(w) = 1.0134479583680545
❌ Transformation is NOT linear
j
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 1.3052796904617978 =?= lambda * L(v) = 1.1810237552518446
❌ Additivity:   L(v + w) = 1.9284476060242493 =?= L(v) + L(w) = 2.9284476060242493
❌ Transformation is NOT linear
k
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(-0.8975277258479595), np.float64(1.5445598933368831)] =?= lambda * L(v) = [-0.89752773  1.54455989]
✔️ Additivity:   L(v + w) = [np.float64(-2.544019227833875), np.float64(7.493228592091494)] =?= L(v) + L(w) = [-2.54401923  7.49322859]
✔️ Transformation is linear
