# lag Prüfungssolver 9000


In [1]:
import numpy as np
import math
from random import random, randint
from util.core import mnull, mrref, linear_combination, check_linearity
import util.core as co
from IPython.display import display, Math

print(f"Precision: {np.finfo(float).eps}")

Precision: 2.220446049250313e-16


### Polarkoordinaten zu kartesischen Koordinaten NNHCXF

Geben Sie die kartesischen Koordinaten der Vektoren an.
`[vx vy]=r*[cos(phi) sin(phi)]`\
Befehle: `np.array, np.cos, np.sin, print`\
a)


In [2]:
r = 5.0
phi = 216.9  # in Grad
degree = 2 * np.pi / 360  #
vv = r * np.array([np.cos(phi * degree), np.sin(phi * degree)])
print(vv)

[-3.99842329 -3.00210113]


### Beispiel 8.3 Schnittmengen qualitativ: Homogene LGS GL27L6
Ebene $E_1$, $E_2$ und $E_3$ geschnitten. Wie sieht die Schnittmenge $E_1 \land E_2 \land E_3$ aus?

$$ \begin{vmatrix}
0x&+9y&+8z&=&0\\
8x&+9y&+6z&=&0\\
10x&+0y&+6z&=&0
\end{vmatrix}
\quad\rightarrow\quad
\begin{vmatrix}
2x&+0y&+8z&=&0\\
0x&+9y&+8z&=&0\\
0x&+0y&+34z&=&0
\end{vmatrix}$$

In [3]:
print("a)")
lgs = np.array([
    [0,9,8],
    [8,9,6],
    [10,0,6]
])

# print(co.gaussian_elimination(lgs))


a)


### Beispiel 8.12 Homogene lineare Gleichungssysteme 801980
Bestimme die Lösungsmenge der homogenen linearen Gleichungsysteme\
a)
$$ \begin{vmatrix}
E_1:&3x&+3y&+-12z&=&0\\
E_2:&1x&+0y&-4z&=&0\\
E_3:&5x&+2y&-20z&=&0
\end{vmatrix}

In [4]:
lgs = np.array(
    [
        [3, 3, -12],
        [1, 0, -4],
        [5, +2, -20],
    ]
)

print("a)")
co.null_space(lgs)

a)


<IPython.core.display.Math object>

In [5]:
lgs = np.array(
    [
        [3, 5, -5],
        [0, 1, -3],
        [0, 2, -5],
    ]
)

print("b)")
richtungsvektor = mnull(lgs)
print(richtungsvektor) # [] -> keine Richtungsvektoren vorhanden. Nur die Triviale lösung erfüllt das lgs. (0,0,0)

co.null_space(lgs)


b)
[]
Triviale Lösung: []


In [6]:
lgs = np.array(
    [
        [1, 3, 1],
        [0, 1, 1],
        [0, 2, 2],
    ]
)

print("c)")
co.null_space(lgs)

c)


<IPython.core.display.Math object>

### Beispiel 8.13 Richtungsvektoren und NullraumV5JXDD

Mehrere Richtungsvektoren

$$ \begin{vmatrix}
1x&+2y&+3z&=&0\\
\end{vmatrix}

In [7]:
lgs = np.array(
    [
        [1, 2, 3],
    ]
)
co.null_space(lgs)

<IPython.core.display.Math object>

### Beispiel 8.14 Nullraum QWDLIG

In [8]:
print("a)")
lgs = np.array(
    [
        [5, 6, 1],
    ]
)
co.null_space(lgs, 1)

a)
[[-1.2 -0.2]
 [ 1.   0. ]
 [ 0.   1. ]]


<IPython.core.display.Math object>

### Beispiel 9.22 Linearkombination LQF58M


In [4]:
u = np.array([-6, 6, 9])
v = np.array([0, -2, 1])
w = np.array([0, 7, -7])
l = np.array([-1, 6, 1])

A = np.transpose(np.array([u, v, w])) # must be transposed to get a coefficient matrix
print("a)")
print(-1 * u + 6 * v + 1 * w)

print("b)")
print(A)
print(f"Solution: {np.matmul(A, l)}")

a)
[  6 -11 -10]
b)
[[-6  0  0]
 [ 6 -2  7]
 [ 9  1 -7]]
Solution: [  6 -11 -10]


### Beispiel 9.23 Linearkombination T46Q97


In [5]:
print("a)")
M = np.array([
    [1, -1, 0],
    [6, 0, -5],
    [0, 5, -1]
    ])
v = np.array([-8,+3,-2])

print(np.matmul(M, v))

print("b)")
M = np.array([
    [0, 1, 3],
    [-1, 0, -1],
    [3, 4, 15]
    ])
v = np.array([-4,3,1])

print(np.matmul(M, v))


a)
[-11 -38  17]
b)
[ 6  3 15]


### Beispiel 9.24 Matrix mal Vektor = Einsetzen in Koeffizientenmatrix CNNZ8U


In [6]:
A = np.array([[1, -1, 2], [6, 1, -1]])
x_p = [1, -2, -1]
x_h = [-1, 13, 7]
print("a)")
print(np.dot(A, x_p))
print("b)")
print(np.matmul(A, x_p))  # matmul = matrix produkt
print("c)")
print(np.dot(A, x_p))

a)
[1 5]
b)
[1 5]
c)
[1 5]


# Kapitel 10 Lineare Abbildungen


### Beispiel 10.3 Linearitat IMSW1Y


In [7]:
print("a)")
w = co.random_vector(3)
check_linearity(3, lambda v: np.dot(v, w))
print("b)")
check_linearity(3, lambda v: 5 * v[0] - v[1] + 1)

a)
✔️ Null Vector:  0.0 is null
✔️ Homogenity:   L(lambda * v) = 0.438781635978789 =?= lambda * L(v) = 0.43878163597878894
✔️ Additivity:   L(v + w) = 1.7396004143516186 =?= L(v) + L(w) = 1.7396004143516186
✔️ Transformation is linear
b)
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 2.080498784829306 =?= lambda * L(v) = 1.4800804908960539
❌ Additivity:   L(v + w) = 6.362542394451294 =?= L(v) + L(w) = 7.362542394451294
❌ Transformation is NOT linear


### Beispiel 10.8 Linearität YHRNU8


In [8]:
print("a")
gamma = random()
check_linearity(2, lambda v: [math.cos(gamma) * v[0], math.sin(gamma) * v[1]])
print("b")
check_linearity(2, lambda v: np.dot(v, v))
print("c")
check_linearity(2, lambda v: 5 * v[0] + 2 * v[1])
print("d")
check_linearity(2, lambda v: np.multiply(-1, v))

a
✔️ Null Vector:  [np.float64(0.0), np.float64(0.0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.02778609358705563), np.float64(0.08857637510748513)] =?= lambda * L(v) = [0.02778609 0.08857638]
✔️ Additivity:   L(v + w) = [np.float64(0.4140822910460365), np.float64(0.9052516088717555)] =?= L(v) + L(w) = [0.41408229 0.90525161]
✔️ Transformation is linear
b
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.5254560899236281 =?= lambda * L(v) = 0.5621847530614797
❌ Additivity:   L(v + w) = 0.7216489245935287 =?= L(v) + L(w) = 0.615507324573891
❌ Transformation is NOT linear
c
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(lambda * v) = 2.634924555679167 =?= lambda * L(v) = 2.634924555679167
✔️ Additivity:   L(v + w) = 6.946933726678719 =?= L(v) + L(w) = 6.946933726678719
✔️ Transformation is linear
d
✔️ Null Vector:  [0 0] is null
✔️ Homogenity:   L(lambda * v) = [-0.8667017  -0.74206796] =?= lambda * L(v) = [-0.8667017  -0.74206796]
✔️ Additivity:   L(v + w) = [-1.0

In [9]:
print("e")
check_linearity(2, lambda v: [math.cos(v[0]), math.sin(v[1])])
print("f")
check_linearity(2, lambda v: [0, v[0] * v[1]])
print("g")
check_linearity(2, lambda v: [v[0] + v[1], v[0]])
print("h")
check_linearity(2, lambda v: v[0])

e
❌ Null Vector:  [1.0, 0.0] is NOT null
❌ Homogenity:   L(lambda * v) = [0.992880276395759, 0.08979537974473253] =?= lambda * L(v) = [0.19398112 0.08754083]
❌ Additivity:   L(v + w) = [0.5806232350905884, 0.9004944313793258] =?= L(v) + L(w) = [1.77528414 1.04944006]
❌ Transformation is NOT linear
f
✔️ Null Vector:  [0, np.int64(0)] is null
❌ Homogenity:   L(lambda * v) = [0, np.float64(0.0002169694540121172)] =?= lambda * L(v) = [0.         0.00234232]
❌ Additivity:   L(v + w) = [0, np.float64(0.16957071990592634)] =?= L(v) + L(w) = [0.         0.07507161]
❌ Transformation is NOT linear
g
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.4467544441082736), np.float64(0.016489245405972186)] =?= lambda * L(v) = [0.44675444 0.01648925]
✔️ Additivity:   L(v + w) = [np.float64(2.3989082647743896), np.float64(0.8103567101941967)] =?= L(v) + L(w) = [2.39890826 0.81035671]
✔️ Transformation is linear
h
✔️ Null Vector:  0 is null
✔️ Homogenity: 

In [10]:
print("i")
check_linearity(2, lambda v: v[0] ** 2)
print("j")
check_linearity(2, lambda v: v[0] + 1)
print("k")
check_linearity(2, lambda v: [3 * v[0] - 4 * v[1], v[0] + 5 * v[1]])

i
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.002519885921863186 =?= lambda * L(v) = 0.027067509186317458
❌ Additivity:   L(v + w) = 2.0042074287967 =?= L(v) + L(w) = 1.058982796734354
❌ Transformation is NOT linear
j
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 1.919569974890467 =?= lambda * L(v) = 1.8611201780945248
❌ Additivity:   L(v + w) = 2.9397201604267846 =?= L(v) + L(w) = 3.9397201604267846
❌ Transformation is NOT linear
k
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(-1.978857952834168), np.float64(4.562953438205952)] =?= lambda * L(v) = [-1.97885795  4.56295344]
✔️ Additivity:   L(v + w) = [np.float64(-2.896652130969329), np.float64(8.565047889992867)] =?= L(v) + L(w) = [-2.89665213  8.56504789]
✔️ Transformation is linear
