# lag Prüfungssolver 9000


In [2]:
import numpy as np
import math
from random import random, randint
from util.core import mnull, mrref, linear_combination, check_linearity
import util.core as co

print(f"Precision: {np.finfo(float).eps}")

Precision: 2.220446049250313e-16


### Polarkoordinaten zu kartesischen Koordinaten NNHCXF

Geben Sie die kartesischen Koordinaten der Vektoren an.
`[vx vy]=r*[cos(phi) sin(phi)]`\
Befehle: `np.array, np.cos, np.sin, print`\
a)


In [3]:
r = 5.0
phi = 216.9  # in Grad
degree = 2 * np.pi / 360  #
vv = r * np.array([np.cos(phi * degree), np.sin(phi * degree)])
print(vv)

[-3.99842329 -3.00210113]


### Beispiel 9.22 Linearkombination LQF58M


In [4]:
u = np.array([-6, 6, 9])
v = np.array([0, -2, 1])
w = np.array([0, 7, -7])
l = np.array([-1, 6, 1])

A = np.array([u, v, w])

print("a)")
print(-1 * u + 6 * v + 1 * w)

print("b)")
print(A)  # must be transposed to get a coefficient matrix
A = np.transpose(A)
print(A)
print(f"Solution: {np.matmul(A, l)}")

a)
[  6 -11 -10]
b)
[[-6  6  9]
 [ 0 -2  1]
 [ 0  7 -7]]
[[-6  0  0]
 [ 6 -2  7]
 [ 9  1 -7]]
Solution: [  6 -11 -10]


### Beispiel 9.23 Linearkombination T46Q97


In [ ]:
print("a)")
Ma = np.array([[1, -1, 0], [6, 0, -5], [0, 5, -1]])

Ma = np.array([[1, -1, 0], [6, 0, -5], [0, 5, -1]])

a)


### Beispiel 9.24 Matrix mal Vektor = Einsetzen in Koeffizientenmatrix CNNZ8U


In [ ]:
A = np.array([[1, -1, 2], [6, 1, -1]])
x_p = [1, -2, -1]
x_h = [-1, 13, 7]
print("a)")
print(np.dot(A, x_p))
print("b)")
print(np.matmul(A, x_p))  # matmul = matrix produkt
print("c)")
print(np.dot(A, x_p))

a)
[1 5]
b)
[1 5]
c)
[1 5]


# Kapitel 10 Lineare Abbildungen


### Beispiel 10.3 Linearitat IMSW1Y


In [6]:
print("a)")
w = co.random_vector(3)
check_linearity(3, lambda v: np.dot(v, w))
print("b)")
check_linearity(3, lambda v: 5 * v[0] - v[1] + 1)

a)
✔️ Null Vector:  0.0 is null
✔️ Homogenity:   L(lambda * v) = 1.2254156124489426 =?= lambda * L(v) = 1.2254156124489426
✔️ Additivity:   L(v + w) = 2.461658263787648 =?= L(v) + L(w) = 2.4616582637876476
✔️ Transformation is linear
b)
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 0.7684906360889987 =?= lambda * L(v) = 0.23242490167181262
❌ Additivity:   L(v + w) = 3.473354052956467 =?= L(v) + L(w) = 4.473354052956467
❌ Transformation is NOT linear


### Beispiel 10.8 Linearität YHRNU8


In [ ]:
print("a")
gamma = random()
check_linearity(2, lambda v: [math.cos(gamma) * v[0], math.sin(gamma) * v[1]])
print("b")
check_linearity(2, lambda v: np.dot(v, v))
print("c")
check_linearity(2, lambda v: 5 * v[0] + 2 * v[1])
print("d")
check_linearity(2, lambda v: np.multiply(-1, v))

a
✔️ Null Vector:  [np.float64(0.0), np.float64(0.0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.16617739283087685), np.float64(0.013212974181233508)] =?= lambda * L(v) = [0.16617739 0.01321297]
✔️ Additivity:   L(v + w) = [np.float64(1.2097938763318736), np.float64(0.08973051613694465)] =?= L(v) + L(w) = [1.20979388 0.08973052]
✔️ Transformation is linear
b
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.8126065433268072 =?= lambda * L(v) = 0.8261196212968664
❌ Additivity:   L(v + w) = 2.735693298050151 =?= L(v) + L(w) = 1.6478002719414504
❌ Transformation is NOT linear
c
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(lambda * v) = 4.1518375619584775 =?= lambda * L(v) = 4.1518375619584775
✔️ Additivity:   L(v + w) = 7.316117063831869 =?= L(v) + L(w) = 7.316117063831869
✔️ Transformation is linear
d
✔️ Null Vector:  [0 0] is null
✔️ Homogenity:   L(lambda * v) = [-0.5019646 -0.5151235] =?= lambda * L(v) = [-0.5019646 -0.5151235]
✔️ Additivity:   L(v + w) = [-1.0

In [ ]:
print("e")
check_linearity(2, lambda v: [math.cos(v[0]), math.sin(v[1])])
print("f")
check_linearity(2, lambda v: [0, v[0] * v[1]])
print("g")
check_linearity(2, lambda v: [v[0] + v[1], v[0]])
print("h")
check_linearity(2, lambda v: v[0])

e
❌ Null Vector:  [1.0, 0.0] is NOT null
❌ Homogenity:   L(lambda * v) = [0.999868011792786, 0.04394995086839322] =?= lambda * L(v) = [0.04605709 0.0382403 ]
❌ Additivity:   L(v + w) = [0.5829543860971379, 0.9243651019658518] =?= L(v) + L(w) = [1.76167518 1.0583904 ]
❌ Transformation is NOT linear
f
✔️ Null Vector:  [0, np.int64(0)] is null
❌ Homogenity:   L(lambda * v) = [0, np.float64(0.09640977745432235)] =?= lambda * L(v) = [0.         0.11422817]
❌ Additivity:   L(v + w) = [0, np.float64(0.5223921452759842)] =?= L(v) + L(w) = [0.         0.26111276]
❌ Transformation is NOT linear
g
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.3991602667198936), np.float64(0.27922127530697205)] =?= lambda * L(v) = [0.39916027 0.27922128]
✔️ Additivity:   L(v + w) = [np.float64(2.1425734325940047), np.float64(1.3394480500186026)] =?= L(v) + L(w) = [2.14257343 1.33944805]
✔️ Transformation is linear
h
✔️ Null Vector:  0 is null
✔️ Homogenity:   L(

In [9]:
print("i")
check_linearity(2, lambda v: v[0] ** 2)
print("j")
check_linearity(2, lambda v: v[0] + 1)
print("k")
check_linearity(2, lambda v: [3 * v[0] - 4 * v[1], v[0] + 5 * v[1]])

i
✔️ Null Vector:  0 is null
❌ Homogenity:   L(lambda * v) = 0.03783537479090869 =?= lambda * L(v) = 0.13026734176921448
❌ Additivity:   L(v + w) = 0.8303542193861969 =?= L(v) + L(w) = 0.5068467994100485
❌ Transformation is NOT linear
j
❌ Null Vector:  1 is NOT null
❌ Homogenity:   L(lambda * v) = 1.2913607103622702 =?= lambda * L(v) = 0.7277081892094786
❌ Additivity:   L(v + w) = 1.8110284877265794 =?= L(v) + L(w) = 2.8110284877265794
❌ Transformation is NOT linear
k
✔️ Null Vector:  [np.int64(0), np.int64(0)] is null
✔️ Homogenity:   L(lambda * v) = [np.float64(0.30680691087685397), np.float64(0.8341728374568294)] =?= lambda * L(v) = [0.30680691 0.83417284]
✔️ Additivity:   L(v + w) = [np.float64(1.4706897439287165), np.float64(6.768295112336469)] =?= L(v) + L(w) = [1.47068974 6.76829511]
✔️ Transformation is linear
